/* 
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

function chkComm() {
    var val1 = parseInt(document.getElementById("amount").value);
    
    var val2 = 10;
    
    var comm = document.getElementById("com");
    
    comm.value = val2;
    
    var pay = document.getElementById("payy");
    
    pay.value = "GHc "+val1 * val2;
    
    var instruct = document.getElementById("instructions");
    
    var select = document.getElementById("select");
    
    var option = select.options[select.selectedIndex].value;
    
    if(option == "mobilemoney") {
        document.getElementById("hidethis").style.display = '';
        var msg1 = "this is option for mobile money. pay ur mobile money using the order id generated by the system as a reference number. Thanks";
        instruct.value = msg1;
        
    } else {
        document.getElementById("hidethis").style.display = '';
        var msg2 = "this is option for bank. Go to the nearest bank and make your bank deposit. Login to the system and confirm payments. Thanks.";
        instruct.value = msg2;
    }
}


